image: node:latest

pages:
  cache:
    paths:
    - node_modules/
  script:
  - npm install
  - npm run build
  - rm -rf public
  - mv build public
  variables: 
    CI: "true"
  artifacts:
    paths:
    - public
  only:
  - master
