image: node:latest

pages:
  stage: deploy
  script:
  - npm cache clean --force
  - npm install --logevel verbose
  - npm run build
  - rm -rf public
  - mv build public
  artifacts:
    paths:
    - public
  only:
  - master
  artifacts:
    paths:
    - /log.txt
    when: on_failure
    expire_in: 1 day